procesar:
    type: rest
    resource: App\Controller\GeneralWSController
#    controller: App\Controller\DefaultController::index

procesarInventario:
    type: rest
    resource: App\Controller\InventariosWSController

procesarLogin:
    type: rest
    resource: App\Controller\LoginWSController
#   controller: App\Controller\DefaultController::index
