<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container99ZOhrL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container99ZOhrL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container99ZOhrL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container99ZOhrL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container99ZOhrL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '99ZOhrL',
    'container.build_id' => '97b8b9b6',
    'container.build_time' => 1574012968,
], __DIR__.\DIRECTORY_SEPARATOR.'Container99ZOhrL');
